// Generated by web_artifact_build from server/src/privileged.ts. Do not edit.
import { definePrivilegedContracts, z } from "@hatch/space-sdk";

export const privileged = definePrivilegedContracts({
  writeAlertUploadChunk: {
    request: z.object({
      uploadId: z.string().uuid(),
      chunkBase64: z.string().min(1).max(600_000),
      reset: z.boolean(),
    }),
    response: z.object({ ok: z.boolean(), error: z.string().nullable() }),
    timeoutMs: 15_000,
  },
  discardAlertUpload: {
    request: z.object({ uploadId: z.string().uuid() }),
    response: z.object({ ok: z.boolean() }),
    timeoutMs: 10_000,
  },
  extractAlertText: {
    request: z.object({
      uploadId: z.string().uuid(),
      fileName: z.string().min(1).max(240),
      password: z.string().max(200).optional(),
    }),
    response: z.object({
      ok: z.boolean(),
      text: z.string(),
      manifestJson: z.string(),
      kind: z.string(),
      truncated: z.boolean(),
      error: z.string().nullable(),
    }),
    timeoutMs: 30_000,
  },
  jevEvaluate: {
    request: z.object({
      state: z.string().min(1).max(30_000),
      questionsJson: z.string().min(2).max(20_000),
    }),
    response: z.object({ ok: z.boolean(), dataJson: z.string().nullable(), error: z.string().nullable(), durationMs: z.number().int().nonnegative() }),
    capabilities: ["network"],
    timeoutMs: 45_000,
  },
  shodanEntity: {
    request: z.object({ entity: z.string().min(1).max(300), kind: z.enum(["ip", "domain"]) }),
    response: z.object({ ok: z.boolean(), dataJson: z.string().nullable(), error: z.string().nullable(), durationMs: z.number().int().nonnegative() }),
    capabilities: ["network"],
    timeoutMs: 45_000,
  },
  virustotalLookup: {
    request: z.object({ path: z.string().min(1).max(900).regex(/^[A-Za-z0-9_./?=&%-]+$/), delayMs: z.number().int().min(0).max(20_000) }),
    response: z.object({ ok: z.boolean(), dataJson: z.string().nullable(), error: z.string().nullable(), durationMs: z.number().int().nonnegative() }),
    capabilities: ["network"],
    timeoutMs: 210_000,
  },
  abuseIpdbLookup: {
    request: z.object({ ip: z.string().min(7).max(45) }),
    response: z.object({ ok: z.boolean(), dataJson: z.string().nullable(), error: z.string().nullable(), durationMs: z.number().int().nonnegative() }),
    capabilities: ["network"],
    timeoutMs: 75_000,
  },
  claudeComplete: {
    request: z.object({ mode: z.enum(["questions", "tiebreak"]), stateJson: z.string().min(2).max(80_000) }),
    response: z.object({ ok: z.boolean(), dataJson: z.string().nullable(), error: z.string().nullable(), durationMs: z.number().int().nonnegative() }),
    capabilities: ["network"],
    timeoutMs: 120_000,
  },
});
